SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INTERVIEW](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[job_id] [int] NOT NULL,
	[candidate_id] [int] NOT NULL,
	[date] [date] NULL,
	[remarks] [varchar](max) NULL,
	[hired] [bit] NULL,
CONSTRAINT [PK_INTERVIEW] PRIMARY KEY CLUSTERED 
( [job_id] ASC,
	[candidate_id] ASC
) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CANDIDATE](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](50) NULL,
	[location] [varchar](50) NULL,
	[email] [varchar](50) NULL,
	[phone] [varchar](10) NULL,
	[registration_date] [date] NULL,
CONSTRAINT [PK_CANDIDATE] PRIMARY KEY CLUSTERED 
(
	[id] ASC
) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[JOB](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[title] [varchar](100) NULL,
	[location] [varchar](50) NULL,
	[salary] [money] NULL,
    [description] [varchar](max) NULL,
	[active] [bit] NULL,
CONSTRAINT [PK_JOB] PRIMARY KEY CLUSTERED 
(
	[id] ASC
) WITH (PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INTERVIEW] WITH CHECK ADD CONSTRAINT [FK_INTERVIEW_CANDIDATE] FOREIGN KEY([candidate_id])
REFERENCES [dbo].[CANDIDATE] ([id])
GO
ALTER TABLE [dbo].[INTERVIEW] CHECK CONSTRAINT [FK_INTERVIEW_CANDIDATE]
GO
ALTER TABLE [dbo].[INTERVIEW] WITH CHECK ADD CONSTRAINT [FK_INTERVIEW_JOB] FOREIGN KEY([job_id])
REFERENCES [dbo].[JOB] ([id])
GO
ALTER TABLE [dbo].[INTERVIEW] CHECK CONSTRAINT [FK_INTERVIEW_JOB]
GO